Ex. 1
anchietajunior/front-end-starting pull request #1
Opened 2021-08-11 21:10 UTC by leandromeyer123

Tabela usando os dados do API (não consegui puxar os santos do dia porque estava em outro API).

2021-08-11 21:18 UTC, anchietajunior requested changes

2021-08-11 21:18 UTC, anchietajunior commented on index.js
>      })
Pode remover esse segundo fetch, deixa só o primeiro mesmo.

2021-08-11 21:18 UTC, anchietajunior commented on index.js
> +            tbody.appendChild(tr);
Tenta colocar o conteúdo dentro de "celebrations" que é onde tem o nome do santo na tabela

![Screen Shot 2021-08-11 at 18 17 28](https://user-images.githubusercontent.com/8007754/129104655-7ca4cd49-b562-4a70-a7ad-3ef374448cb1.png)

2021-08-11 21:18 UTC, anchietajunior commented on index.js
> +
Tenta criar um header pra essa tabela, indicando o que cada coluna significa.

2021-08-17 00:55 UTC, leandromeyer123 commented
Anchieta, o primeiro "second version" é o que tem alterações mais substanciais. O segundo eu fiz porque tinha perdido umas alterações de estilo essencialmente e subi de novo, mas não muda quase nada (eu não sabia que ao eu fazer o push ele já ia aparecer aqui.

2021-08-23 13:20 UTC, merged